### ISSUE TITLE
Modify offcanvas and other elements CSS

### ISSUE THREAD

**Issue by alessio619** [JohnCoene/bsutils#3]
Hi, I am very interested in adding many of the UI elements in the package, they are really easy to implement and useful. I've tried to add a `tags$style(".offcanvas {background-color: #000000}")` and other workarounds but I cannot change the buttons properties such as width and color.

Thanks!

**Comment by JohnCoene** [comment]
Do you have an example of shiny application where this fails?

**Comment by alessio619** [comment]
I leave the very same reprez in your page, I wonder how can I change the button' s color:

`ui <- fluidPage(
  theme = bslib::bs_theme(version = 5L, bootswatch = 'zephyr'),
  offcanvas(
    offcanvasButton(
      "Open"
    ),
    offcanvasContent(
      offcanvasHeader(
        "Off canvas"
      ),
      p(
        "Hello world"
      )
    )
  )
)

server <- \(input, output, session){}

shinyApp(ui, server)
`

**Comment by JohnCoene** [comment]
And if below `theme` you add

```
tags$head(
  tags$style(
    ".offcanvas {background-color: #000000 }")
)
```

It does not work?

(Sorry no laptop access right now)

**Comment by alessio619** [comment]
Works perfectly. Thanks
